allowBuilds:
  esbuild: true
  rehype-tree-sitter: true
  sharp: true
minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri@0.3.2'
  - '@astrojs/starlight@0.41.0'
  - astro@7.0.2
  - '@astrojs/internal-helpers@0.10.3'
  - '@astrojs/markdown-satteri@0.3.6'
  - astro@7.2.3
